INSERT INTO `gram_topics` (`Title`, `Level`, `ImageURL`, `Description`) VALUES ("To Be","A1","https://globalgoalsesl.files.wordpress.com/2020/07/verb-tobe.jpg","The verb to BE can refer to the present past or future.  It’s the most common and most irregular verb in English.");
INSERT INTO `gram_topics` (`Title`, `Level`, `ImageURL`, `Description`) VALUES ("Here There","A1","https://thumbs.dreamstime.com/b/here-there-antonyms-word-card-vector-template-opposites-concept-here-there-antonyms-word-card-vector-template-opposites-194733501.jpg","Here, there, and everywhere are pronouns of space, designating the same thing from the first, second, and third-person perspectives.");
INSERT INTO `gram_topics` (`Title`, `Level`, `ImageURL`, `Description`) VALUES ("Like","A1","https://vn.plainmemory.com/wp-content/uploads/2021/01/like.jpg","Present perfect tense is one of the commonly used verb tenses in English. It describes unfinished actions, experiences or actions without a definite time in the past");
INSERT INTO `gram_topics` (`Title`, `Level`, `ImageURL`, `Description`) VALUES ("Personal Pronouns","A1","https://i.ytimg.com/vi/7UC4RQhGo54/maxresdefault.jpg", "Personal pronouns are the stunt doubles of grammar; they stand in for the people (and perhaps animals) who star in our sentences");
INSERT INTO `gram_topics` (`Title`, `Level`, `ImageURL`, `Description`) VALUES ("Possessive 's","A1","https://i.ytimg.com/vi/-rMV2oMDRHo/maxresdefault.jpg", "Possessive pronouns do exactly what it seems like they should do. They are the pronouns that help us show possession or ownership in a sentence");
INSERT INTO `gram_topics` (`Title`, `Level`, `ImageURL`, `Description`) VALUES ("Present Simple","A1","https://englishclassviaskype.com/wp-content/uploads/2019/12/Present-simple-explained-in-pictures.png","The present simple tense isn't always so simple for learners but I promise this explanation will make things much clearer. In this section, we'll look at the different uses of the present tense");
INSERT INTO `gram_topics` (`Title`, `Level`, `ImageURL`, `Description`) VALUES ("This/That/These","A1","https://i.ytimg.com/vi/GIbD5seHH-E/maxresdefault.jpg", "We use this/that/these/those to explain what we are talking about");
INSERT INTO `gram_topics` (`Title`, `Level`, `ImageURL`, `Description`) VALUES ("Was/Were","A1","https://i0.wp.com/teachers.onlineenglishexpert.com/wp-content/uploads/2013/09/Teaching-Past-Simple-Of-To-Be-English-Grammar-For-Beginners.jpg?ssl=1", "Actually, was/were are the past tense form of the verb “to be”");
INSERT INTO `gram_topics` (`Title`, `Level`, `ImageURL`, `Description`) VALUES ("Articles","A2","https://www.albert-learning.com/catalogue/img/english_articles_600x350.png", "English has two articles: the and a/an. The is used to refer to specific or particular nouns; a/an is used to modify non-specific or non-particular nouns. We call the the definite article and a/an the indefinite article");
INSERT INTO `gram_topics` (`Title`, `Level`, `ImageURL`, `Description`) VALUES ("Adverbs- describing verbs","A2","https://i.ytimg.com/vi/yFPS8yTS_Gw/maxresdefault.jpg", "An adverb is a word that modifies (describes) a verb (he sings loudly), an adjective (very tall), another adverb (ended too quickly)");
INSERT INTO `gram_topics` (`Title`, `Level`, `ImageURL`, `Description`) VALUES ("Adverbial Phrases","A2","https://i.ytimg.com/vi/1an0ZjR0zek/maxresdefault.jpg", "An adverbial phrase is a group of words that functions as an adverb. 'In the morning' and 'behind the shed' are examples of adverbial phrases");
INSERT INTO `gram_topics` (`Title`, `Level`, `ImageURL`, `Description`) VALUES ("Can/Could","A2","https://i.ytimg.com/vi/xE-04vBz3fg/maxresdefault.jpg", "Be able to is possible in all tenses - but CAN is possible only in the present and COULD is possible only in the past for ability. In addition, CAN and COULD have no infinitive form");
INSERT INTO `gram_topics` (`Title`, `Level`, `ImageURL`, `Description`) VALUES ("Comparative adjectives","A2","https://i.ytimg.com/vi/twZS6OD59aE/maxresdefault.jpg", "When we talk about two things, we can COMPARE them. We can see if they are the same or different");
INSERT INTO `gram_topics` (`Title`, `Level`, `ImageURL`, `Description`) VALUES ("First Conditional","A2","https://i.pinimg.com/originals/b0/3f/9a/b03f9a5668c115dfa880e483ed599692.jpg", "The first conditional describes things that I think are likely to happen in the future");
INSERT INTO `gram_topics` (`Title`, `Level`, `ImageURL`, `Description`) VALUES ("Gerunds & Indinitives","A2","https://i.ytimg.com/vi/MG94r74uVrA/maxresdefault.jpg", "It can be a little difficult to know when to use gerunds and infinitives");
INSERT INTO `gram_topics` (`Title`, `Level`, `ImageURL`, `Description`) VALUES ("Going to","A2","https://i.ytimg.com/vi/U8L2m8TeIWA/maxresdefault.jpg", "We use going to when we have the intention to do something before we speak. We have already made a decision before speaking");
INSERT INTO `gram_topics` (`Title`, `Level`, `ImageURL`, `Description`) VALUES ("Have to","A2","https://tienganhfree.com/wp-content/uploads/2020/09/c%C3%B4ng-th%E1%BB%A9c-have-to-1024x640.png", "Use of have to. In general, have to expresses impersonal obligation");
INSERT INTO `gram_topics` (`Title`, `Level`, `ImageURL`, `Description`) VALUES ("How questions","A2","https://st.depositphotos.com/1745098/3412/i/950/depositphotos_34127839-stock-photo-how-word.jpg", "We use how when we introduce direct and indirect questions");
INSERT INTO `gram_topics` (`Title`, `Level`, `ImageURL`, `Description`) VALUES ("Imperative forms","A2","https://images.twinkl.co.uk/tw1n/image/private/t_630/image_repo/5f/3a/t2-e-5030--imperative-verbs-activity-powerpoint-_ver_2.jpg", "You can use the imperative form to give an order, to give a warning or advice, and (if you use “please”) to make a request");
INSERT INTO `gram_topics` (`Title`, `Level`, `ImageURL`, `Description`) VALUES ("Past continuous","A2","https://i.ytimg.com/vi/UeKZ6Mm-SlY/maxresdefault.jpg","Past continuous tense is used to express a continued or ongoing action in past or to indicate that longer action in the past was interrupted");
INSERT INTO `gram_topics` (`Title`, `Level`, `ImageURL`, `Description`) VALUES ("Past simple","A2","https://vskills.in/certification/blog/wp-content/uploads/2014/11/past-an-opportunity-or-an-obstacle.png","An age old habit of humans is the reminiscence of the past. We keep the memories of the past intact to us wishing if we could have changed things");
INSERT INTO `gram_topics` (`Title`, `Level`, `ImageURL`, `Description`) VALUES ("Present continuous","A2","https://i.ytimg.com/vi/lPY9sYK5S5A/maxresdefault.jpg","This tense is formed using the auxiliary verb have/has plus the past participle of the verb be (been) plus the -ing form of the main verb. We'll learn how to make positive and negative forms, short forms (contractions) and questions");
INSERT INTO `gram_topics` (`Title`, `Level`, `ImageURL`, `Description`) VALUES ("Present continuous for future","A2","http://yourenglishlessons.files.wordpress.com/2010/04/future2.gif", "Use the same way with present continuous, but they are talking about future");
INSERT INTO `gram_topics` (`Title`, `Level`, `ImageURL`, `Description`) VALUES ("Present Perfect","A2","https://i.ytimg.com/vi/SSIZidvE-lc/maxresdefault.jpg","Present perfect tense is one of the commonly used verb tenses in English. It describes unfinished actions, experiences or actions without a definite time in the past");
INSERT INTO `gram_topics` (`Title`, `Level`, `ImageURL`, `Description`) VALUES ("Should/Ought to","A2","https://i.ytimg.com/vi/PGMQZEIXBMs/maxresdefault.jpg","We use SHOULD when we want to say or ask what is the correct or best thing to do. It is a way of asking for or giving advice. Note: In this meaning, we can also use OUGHT TO instead of SHOULD");
INSERT INTO `gram_topics` (`Title`, `Level`, `ImageURL`, `Description`) VALUES ("Some/any/much/many","A2","https://image.slidesharecdn.com/some-any-alotof-much-many-abit-121017134000-phpapp01/95/some-anya-lot-of-much-many-a-bit-1-638.jpg?cb=1350481300","The differences between some and any, and also, much, many, and a lot, often cause difficulties for learners");
INSERT INTO `gram_topics` (`Title`, `Level`, `ImageURL`, `Description`) VALUES ("Subject & Object questions","A2","https://image.slidesharecdn.com/subjectobjectquestionsweb-101217111321-phpapp02/95/subject-object-questions-1-728.jpg?cb=1292585028","In subject questions where we want to find information about the subject, we do not use the auxiliary verb do/does/did");
INSERT INTO `gram_topics` (`Title`, `Level`, `ImageURL`, `Description`) VALUES ("Will/won't","A2","https://i.ytimg.com/vi/n14zCZAvSjI/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLBEU4dTg9uQs9mhoHJFeY2ocqA7cQ","“Will” and the negative form “will not” or “won't” is a modal auxiliary verb");
INSERT INTO `gram_topics` (`Title`, `Level`, `ImageURL`, `Description`) VALUES ("Zero conditinal","A2","https://i.ytimg.com/vi/r7UW7EJuR3o/maxresdefault.jpg","The zero conditional is used to make statements about the real world, and often refers to general truths, such as scientific facts");
INSERT INTO `gram_topics` (`Title`, `Level`, `ImageURL`, `Description`) VALUES ("Would like vs like","A2","https://s3-eu-west-1.amazonaws.com/uploads.playbaamboozle.com/uploads/images/69723/1600028495_97651","It is used as a polite way of asking for something, or showing someone else prefers something");
INSERT INTO `gram_topics` (`Title`, `Level`, `ImageURL`, `Description`) VALUES ("Both, either, neither","B1","https://cdn.slidesharecdn.com/ss_thumbnails/both-either-neither-111027032446-phpapp02-thumbnail-4.jpg?cb=1319686011","Used alone (i.e. when not followed by or or by nor) either and neither are used in the same way as both");
INSERT INTO `gram_topics` (`Title`, `Level`, `ImageURL`, `Description`) VALUES ("Conditional 2nd","B1","https://image.slidesharecdn.com/conditional2-190327121517/95/second-conditional-1-638.jpg?cb=1553689070","The Second Conditional. The second conditional uses the past simple after if, then 'would' and the infinitive");
INSERT INTO `gram_topics` (`Title`, `Level`, `ImageURL`, `Description`) VALUES ("Conditional 3rd","B1","https://englishclassviaskype.com/wp-content/uploads/2019/07/Using-the-3rd-conditional-to-express-regrets.png", "We use the third conditional (if + past perfect, would + have + past participle) to talk about something in the past that did not happen");
INSERT INTO `gram_topics` (`Title`, `Level`, `ImageURL`, `Description`) VALUES ("Embeded quesitons","B1","https://d356qujqspw52j.cloudfront.net/img/full/03-28-Ethnic-background.jpg?__SQUARESPACE_CACHEVERSION=1301368197886", "An embedded question is a type of question which is included within another question or sentence. It is different from other types of questions");
INSERT INTO `gram_topics` (`Title`, `Level`, `ImageURL`, `Description`) VALUES ("Future Continuous","B1","https://i.ytimg.com/vi/eOs0cZ12Fhk/maxresdefault.jpg","In the same way as with the future simple, usually we use the short form (‘ll be verb-ing) when we are speaking");
INSERT INTO `gram_topics` (`Title`, `Level`, `ImageURL`, `Description`) VALUES ("So, such, too, enough","B1","https://image.slidesharecdn.com/sosuch-too-enough-160227090802/95/so-such-too-enough-1-638.jpg?cb=1456566554", "We use so, such, enough and too to indicate degree. So and such give emphasis and mean 'very'");
INSERT INTO `gram_topics` (`Title`, `Level`, `ImageURL`, `Description`) VALUES ("May, might + adverbs of probability","B1","https://englishclassviaskype.com/wp-content/uploads/2019/10/Use-MAY-and-MIGHT-to-speculate-about-the-past-.png", "We use may and might to talk about what will possibly happen in the future, or is possible in the present. They express the same meaning as maybe will");
INSERT INTO `gram_topics` (`Title`, `Level`, `ImageURL`, `Description`) VALUES ("Modals for Recommendations","B1","https://i.ytimg.com/vi/zUrmpxV5SRg/maxresdefault.jpg","Whatever you call them (modals, modal verbs, auxiliaries, auxiliary verbs, etc.), modals are one of the most difficult grammar points for students to grasp");
INSERT INTO `gram_topics` (`Title`, `Level`, `ImageURL`, `Description`) VALUES ("Modals for Deduction","B1","https://englishclassviaskype.com/wp-content/uploads/2019/10/1.png","Some modals of deductions about the past are must have, might have/may have, and can't have/couldn't have");
INSERT INTO `gram_topics` (`Title`, `Level`, `ImageURL`, `Description`) VALUES ("Present Perfect Continuous","B1","https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRXUkl_tcFZX2zy3fUgwPe666q0cFth-mwAeg&usqp=CAU","We use the Present Perfect Continuous to emphasise the duration or continuous course of an action");
INSERT INTO `gram_topics` (`Title`, `Level`, `ImageURL`, `Description`) VALUES ("Present Perfect vs Past Simple","B1","https://vskills.in/certification/blog/wp-content/uploads/2014/11/past-an-opportunity-or-an-obstacle.png","An age old habit of humans is the reminiscence of the past. We keep the memories of the past intact to us wishing if we could have changed things");
INSERT INTO `gram_topics` (`Title`, `Level`, `ImageURL`, `Description`) VALUES ("Passives","B1","http://www.eslprintables.com/powerpointpreviews/70794_1-PASSIVE_VOICE_ALL_TENSES.jpg","We make the passive by putting the verb 'to be' into whatever tense we need and then adding the past participle");
INSERT INTO `gram_topics` (`Title`, `Level`, `ImageURL`, `Description`) VALUES ("Past Perfect","B1","https://i.ytimg.com/vi/-TrE6VdtgLE/maxresdefault.jpg","The Past Perfect is a verb tense used to express actions that occurred in the past and finished before another action in the past");
INSERT INTO `gram_topics` (`Title`, `Level`, `ImageURL`, `Description`) VALUES ("Question Tags","B1","https://i.ytimg.com/vi/48Kd3UXqwNA/maxresdefault.jpg","Tag questions (or question tags) turn a statement into a question");
INSERT INTO `gram_topics` (`Title`, `Level`, `ImageURL`, `Description`) VALUES ("Should have","B1","https://i0.wp.com/www.themantic-education.com/ibpsych/wp-content/uploads/sites/3/2017/07/bigstock-129868211.jpg?fit=906%2C604&ssl=1","Should have means that something did not happen, but we wish it had happened");
INSERT INTO `gram_topics` (`Title`, `Level`, `ImageURL`, `Description`) VALUES ("Future perfect","B2","https://i1.wp.com/examplanning.com/wp-content/uploads/2019/07/Future-Perfect-Tense-Copy-min.jpg?fit=1349%2C811&ssl=1","The future perfect tense in English with future perfect examples. Learn the definition and how to form the future perfect tense with useful examples");
INSERT INTO `gram_topics` (`Title`, `Level`, `ImageURL`, `Description`) VALUES ("Future perfect continuous","B2","https://i0.wp.com/examplanning.com/wp-content/uploads/2019/08/Future-perfect-continuous-tense-2-min.jpg?fit=1387%2C831&ssl=1", "The past future continuous is similar to the future perfect, except that it expresses longer actions in the future before another action in the future");
INSERT INTO `gram_topics` (`Title`, `Level`, `ImageURL`, `Description`) VALUES ("Relative clauses","B2","http://file.hstatic.net/1000295734/file/relative-clause-konu-anlatimi-kullanimi_grande.png","Defining relative clauses are composed of a relative pronoun (sometimes omitted), a verb, and optional other elements such as the subject or object of the verb");
INSERT INTO `gram_topics` (`Title`, `Level`, `ImageURL`, `Description`) VALUES ("Past perfect continuous","B2","https://i.ytimg.com/vi/A3HRUtZCAa4/maxresdefault.jpg", "The Past Perfect Continuous tense or Past Perfect Progressive shows that an action that started in the past continued up until another time in the past");
INSERT INTO `gram_topics` (`Title`, `Level`, `ImageURL`, `Description`) VALUES ("Reported Speech","B2","https://lh3.googleusercontent.com/proxy/p389kQ03d7PhDXMZr3kIlGSv6SZkzMh8xYEbAULlKO9VSPIA9GFoStspb9LLi66rvH3reRb8aScitmW33vAmhkZF2wBMq0kxulbGW3fOnCBE6iKlcw","Reported speech is when we tell someone what another person said. To do this, we can use direct speech or indirect speech");
INSERT INTO `gram_topics` (`Title`, `Level`, `ImageURL`, `Description`) VALUES ("Used to/Would","B2","https://i0.wp.com/teachers.onlineenglishexpert.com/wp-content/uploads/2014/02/Used-To-And-Would-Esl-Lesson-Plan.jpg?fit=700%2C400&ssl=1&w=640","But we use 'used to' for any extended action or situation in the past. 'Would' is only good for actions or situations that were repeated many times");
INSERT INTO `gram_topics` (`Title`, `Level`, `ImageURL`, `Description`) VALUES ("Wish/If only","B2","https://www.englishbix.com/wp-content/uploads/2020/02/Conditionals-I-Wish-or-If-Only-Sentence-Examples--1024x576.jpg", "We can use wish/if only + a past perfect form to talk about something we would like to change about the past");









