INSERT INTO `quiz` (`Title`, `Level`,`Description`) VALUES ("To be & School","A1","Quiz to test how well you know To be & School");
INSERT INTO `quiz` (`Title`, `Level`,`Description`) VALUES ("Here & House","A1","Quiz to test how well you know Here & House");
INSERT INTO `quiz` (`Title`, `Level`,`Description`) VALUES ("Like & Family","A1","Quiz to test how well you know Like & Family");
INSERT INTO `quiz` (`Title`, `Level`,`Description`) VALUES ("Pronouns & Meals","A1","Quiz to test how well you know Pronouns & Meals");
INSERT INTO `quiz` (`Title`, `Level`,`Description`) VALUES ("Possessive & Number","A1","Quiz to test how well you know Possessive & Number");
INSERT INTO `quiz` (`Title`, `Level`,`Description`) VALUES ("Present & Calendar","A1","Quiz to test how well you know Present & Calendar");
INSERT INTO `quiz` (`Title`, `Level`,`Description`) VALUES ("This & People","A1","Quiz to test how well you know This & People");
INSERT INTO `quiz` (`Title`, `Level`,`Description`) VALUES ("Was & Job","A1","Quiz to test how well you know Was & Job");
INSERT INTO `quiz` (`Title`, `Level`,`Description`) VALUES ("Health & Shop","A1","Quiz to test how well you know Health & Shop");
INSERT INTO `quiz` (`Title`, `Level`,`Description`) VALUES ("Clothes & Fruits","A1","Quiz to test how well you know Clothes & Fruits");
INSERT INTO `quiz` (`Title`, `Level`,`Description`) VALUES ("Vegetables & Travel & Sports","A1","Quiz to test how well you know Vegetables & Travel & Sports");
INSERT INTO `quiz` (`Title`, `Level`,`Description`) VALUES ("Articles & Animals","A2","Quiz to test how well you know Articles & Animals");
INSERT INTO `quiz` (`Title`, `Level`,`Description`) VALUES ("Adverbs & Holiday","A2","Quiz to test how well you know Adverbs & Holiday");
INSERT INTO `quiz` (`Title`, `Level`,`Description`) VALUES ("Adverbial Phrases & Supermarket","A2","Quiz to test how well you know Adverbial Phrases & Supermarket");
INSERT INTO `quiz` (`Title`, `Level`,`Description`) VALUES ("Can & Telephoning","A2","Quiz to test how well you know Can & Telephoning");
INSERT INTO `quiz` (`Title`, `Level`,`Description`) VALUES ("Compare & Weather","A2","Quiz to test how well you know Compare & Weather");
INSERT INTO `quiz` (`Title`, `Level`,`Description`) VALUES ("First Conditional & Interests","A2","Quiz to test how well you know First Conditional & Interests");
INSERT INTO `quiz` (`Title`, `Level`,`Description`) VALUES ("Gerunds & Indinitives & Entertainment","A2","Quiz to test how well you know Gerunds & Indinitives & Entertainment");
INSERT INTO `quiz` (`Title`, `Level`,`Description`) VALUES ("Going to & Describing","A2","Quiz to test how well you know Going to & Describing");
INSERT INTO `quiz` (`Title`, `Level`,`Description`) VALUES ("Have to & City & Country","A2","Quiz to test how well you know Have to & City & Country");
INSERT INTO `quiz` (`Title`, `Level`,`Description`) VALUES ("How questions & Imperative forms","A2","Quiz to test how well you know How questions & Imperative forms");
INSERT INTO `quiz` (`Title`, `Level`,`Description`) VALUES ("Past continuous & Past Simple","A2","Quiz to test how well you know Past continuous & Past Simple");
INSERT INTO `quiz` (`Title`, `Level`,`Description`) VALUES ("Present continuous & Present continuous for future","A2","Quiz to test how well you know Present continuous & Present continuous for future");
INSERT INTO `quiz` (`Title`, `Level`,`Description`) VALUES ("Present Perfect & Should","A2","Quiz to test how well you know Present Perfect & Should");
INSERT INTO `quiz` (`Title`, `Level`,`Description`) VALUES ("Amount & Questions","A2","Quiz to test how well you know Amount & Questions");
INSERT INTO `quiz` (`Title`, `Level`,`Description`) VALUES ("Will & Zero Condition & Would like","A2","Quiz to test how well you know Will & Zero Condition & Would like");
INSERT INTO `quiz` (`Title`, `Level`,`Description`) VALUES ("Both & Work","B1","Quiz to test how well you know Both & Work");
INSERT INTO `quiz` (`Title`, `Level`,`Description`) VALUES ("Conditional 2nd & Media","B1","Quiz to test how well you know Conditional 2nd & Media");
INSERT INTO `quiz` (`Title`, `Level`,`Description`) VALUES ("Conditional 3rd & Socialising","B1","Quiz to test how well you know Conditional 3rd & Socialising");
INSERT INTO `quiz` (`Title`, `Level`,`Description`) VALUES ("Embeded quesitons & Celebrations","B1","Quiz to test how well you know Embeded quesitons & Celebrations");
INSERT INTO `quiz` (`Title`, `Level`,`Description`) VALUES ("Future Continuous & Marriage","B1","Quiz to test how well you know Future Continuous & Marriage");
INSERT INTO `quiz` (`Title`, `Level`,`Description`) VALUES ("So, such & Letters","B1","Quiz to test how well you know So, such & Letters");
INSERT INTO `quiz` (`Title`, `Level`,`Description`) VALUES ("May & Cookery","B1","Quiz to test how well you know May & Cookery");
INSERT INTO `quiz` (`Title`, `Level`,`Description`) VALUES ("Modals for Recommendations & Sea","B1","Quiz to test how well you know Modals for Recommendations & Sea");
INSERT INTO `quiz` (`Title`, `Level`,`Description`) VALUES ("Modals for Deduction & Present Perfect Continuous","B1","Quiz to test how well you know Modals for Deduction & Present Perfect Continuous");
INSERT INTO `quiz` (`Title`, `Level`,`Description`) VALUES ("Present Perfect vs Past Simple & Passive","B1","Quiz to test how well you know Present Perfect vs Past Simple & Passive");
INSERT INTO `quiz` (`Title`, `Level`,`Description`) VALUES ("Past Perfect & Question Tags & Should have","B1","Quiz to test how well you know Past Perfect & Question Tags & Should have");
INSERT INTO `quiz` (`Title`, `Level`,`Description`) VALUES ("Future perfect & Economy","B2","Quiz to test how well you know Future perfect & Economy");
INSERT INTO `quiz` (`Title`, `Level`,`Description`) VALUES ("Future perfect continuous & environment","B2","Quiz to test how well you know Future perfect continuous & environment");
INSERT INTO `quiz` (`Title`, `Level`,`Description`) VALUES ("Relative clauses & Driving","B2","Quiz to test how well you know Relative clauses & Driving");
INSERT INTO `quiz` (`Title`, `Level`,`Description`) VALUES ("Past perfect continuous & Tools","B2","Quiz to test how well you know Past perfect continuous & Tools");
INSERT INTO `quiz` (`Title`, `Level`,`Description`) VALUES ("Reported Speech & The senses","B2","Quiz to test how well you know Reported Speech & The senses");
INSERT INTO `quiz` (`Title`, `Level`,`Description`) VALUES ("Used to/Would & Crime & Punishment","B2","Quiz to test how well you know Used to/Would & Crime & Punishment");
INSERT INTO `quiz` (`Title`, `Level`,`Description`) VALUES ("Wish/If only & Age & Education","B2","Quiz to test how well you know Wish/If only & Age & Education");
INSERT INTO `quiz` (`Title`, `Level`,`Description`) VALUES ("Quick Placement & Diagnostic Test", "All","This test has been designed to help you decide which of the 6 levels of English lessons is the most appropriate for you.");



-- quiz_question table
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("1", "How old.............you?", NULL, "text", "single", "am, is, are, be", "3");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("1", "My name............Mai", NULL, "text", "single", "be, is, are, am", "2");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("1", "How .........she?", NULL, "text", "single", "be, is, am, to be", "2");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("1", "Minh...........all right", NULL, "text", "single", "is, am, are, be", "1");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("1", "Lan and I........10 years old", NULL, "text", "single", "are, not are, not be, is", "1");

INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("2", "_____________ two English girls in my school", NULL, "text", "single", "Here is, There are", "2");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("2", "_____________ a good film on tonight?", NULL, "text", "single", "Is there, Are there", "1");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("2", "_____________ a hall in my house", NULL, "text", "single", "There isn't, There aren't", "1");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("2", "_____________ a lot of chairs in the classroom", NULL, "text", "single", "There is, There are", "2");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("2", "_____________ blue curtains in your room?", NULL, "text", "single", "Is there, Are there", "2");

INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("3", "I really like _____________ in the woods", NULL, "text", "single", "walking, to walk, to walking, walk", "1");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("3", "I like to _____________ early on Saturday mornings", NULL, "text", "single", "do the shopping, doing the shopping, done the booking, went", "1");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("3", "Children always like _____________ to stories", NULL, "text", "single", "to listen, listening, listen, be listen", "2");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("3", "When I'm pouring tea I like to _____________ the milk in first", NULL, "text", "single", "putted, be put, put, putting", "3");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("3", "I didn't like to _____________ you at home", NULL, "text", "single", "disturbing, disturb, disturbed, be disturb", "2");

INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("4", "_______ of them has been turned in stone", NULL, "text", "single", "No one, Not one, None, Even one", "2");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("4", "Which thief got a fright? _______ with the money", NULL, "text", "single", "He, Him, That, The one", "4");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("4", "Erna's friends will be on the coast. That's where _______ of them will be", NULL, "text", "single", "more, the most, most, the more", "1");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("4", "We are all very excited_______ are very excited", NULL, "text", "single", "All me, Us all, ALl us, All of us", "4");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("4", "They didn't steal anything. They stole_______", NULL, "text", "single", "anything, not anything, not nothing, nothing", "4");

INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("5", "………………… names are Sam and Michael", NULL, "text", "single", "They’re, He's, his, their", "4");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("5", "……………………… teacher is English", NULL, "text", "single", "They're, He's, his, we", "3");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("5", "……………………… our teacher", NULL, "text", "single", "Their, He's, his, we", "2");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("5", "……………………… family is from Spain", NULL, "text", "single", "She's, He's, His, They", "3");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("5", "……………………… class is in room 10", NULL, "text", "single", "They're, He's, She's, our", "4");

INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("6", "I _____ (be) a student", NULL, "text", "single", "am, is, are", "1");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("6", "My father __________ excuses when I feel like going to the cinema", NULL, "text", "single", "make always, make always, always makes", "3");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("6", "His students ________ (not, speak) German in class", NULL, "text", "single", "don't speak, doesn't speak, not speak", "2");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("6", "She ________ (not, be) six years old", NULL, "text", "single", "isn't, not is, are not", "1");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("6", "John ________ (work) in a supermarket", NULL, "text", "single", "works, working, work", "1");

INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("7", "__________ book is expensive", NULL, "text", "single", "This, These, Those", "1");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("7", "__________ cat is small", NULL, "text", "single", "That, These, Those", "1");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("7", "__________ pens are blue", NULL, "text", "single", "This, That, These", "3");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("7", "__________ movie is funny", NULL, "text", "single", "This is, That, These, Those", "2");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("7", "__________ airplanes are very big", NULL, "text", "single", "This, That, These are, Those", "4");

INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("8", "The weather  ........ cold yesterday", NULL, "text", "single", "aren't, isn't, wasn't, weren't", "3");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("8", "The flight ……. delayed because of bad weather", NULL, "text", "single", "was, were, did, had", "1");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("8", "They ……. leaving for the airport when I last saw them", NULL, "text", "single", "was, were, did, had", "2");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("8", " ……. it raining when you left your office this afternoon?", NULL, "text", "single", "was, were, did, had", "1");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("8", "The employees ……. informed last night that their company was going into receivership", NULL, "text", "single", "was, were, did, had", "2");

INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("9", "The controller of the body is the ____ system. Led by the brain and nerves, it allows us to move, talk and feel emotions", NULL, "text", "single", "circulatory, digestive, nervous, respiratory", "3");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("9", "____ system of the body lets us break down the food we eat and turn it into energy", NULL, "text", "single", "Circulatory, Digestive, Nervous, Respiratory", "2");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("9", "Skeletal system of the body is made up of our ____. It supports our body and protects our organs", NULL, "text", "single", "bones, museles, nerves, vessels", "1");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("9", "In under a minute, your ____ can pump blood to bring oxygen and nutrients to every cell in your body", NULL, "text", "single", "brain, heart, lungs, vessels", "2");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("9", "The human ____ system is a series of organs responsible for taking in oxygen and expelling carbon dioxide", NULL, "text", "single", "circulatory, digestive, nervous, respiratory", "4");

INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("10", "Now fashion ______ want to change the traditional Ao dai", NULL, "text", "single", "makers, workers, designers, dressers", "3");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("10", "The word `Jeans` comes from a kind of ______ that was made in Europe", NULL, "text", "single", "substance, form, element, material", "4");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("10", "In the 18th century Jean cloth was made completely from ______", NULL, "text", "single", "rubber, leather, cotton, nylon", "2");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("10", "In the 1980s jeans finally became high fashion clothing ______ of jeans went up and up", NULL, "text", "single", "Sales, Buying, Selling, Making", "1");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("10", "Today young generation ______ wearing jeans", NULL, "text", "single", "likes, enjoys, in font of, All ABC", "4");

INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("11", "Mary went to Viet Nam last year and it was her second time", NULL, "text", "single", "That was the first time Mary went to Viet Nam, That wasn't the first time Mary went to Viet Nam, That was the second time Mary went to Viet Nam, That was the last time Mary went to Viet Nam", "3");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("11", "There are many places worth seeing in London", NULL, "text", "single", "There are many places of interest in London, There are not many places of interest in London, There are no places of interest in London, There are many places which interesting in London", "1");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("11", "I want to visit a beautiful beach in Viet Nam. Could you suggest one?", NULL, "text", "single", "Do you mind if you suggested one beautiful beach in Viet Nam?, Would you mind if you suggest one beautiful beach in Viet Nam?, Do you mind suggesting one beautiful beach in Viet Nam?, Could you suggested one beautiful beach in Viet Nam?", "3");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("11", "Could you help me to send this letter to my boss?", NULL, "text", "single", "Would you mind sending this letter to my boss?, Do you mind send this letter to my boss?, Would you mind send this letter to my boss?, Would you mind to send this letter to my boss?", "1");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("11", "Yesterday we decided to paddle around West Lake in a canoe", NULL, "text", "single", "We decided to go around West Lake in, a canoe yesterday, We decided to walk around West Lake in a canoe yesterday, We decided to run around West Lake in a canoe yesterday, We decided to ride around West Lake in a canoe yesterday", "4");

INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("12", "We are looking for……place to spend ………night", NULL, "text", "single", "the/the, a/the, a/a, the/a", "");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("12", "I was given …………….beautiful bag on my birthday by my mother", NULL, "text", "single", "a, an, the, ø", "");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("12", "Jack’s father bought him…….bicycle that he had wanted for his birthday", NULL, "text", "single", "a, an, the, ø", "");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("12", "………….Statue of Liberty was a gift of friendship from………..France to………United States", NULL, "text", "single", "the/ ø/ the, the/the/the, ø/the/the, ø/ ø/ the", "");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("12", "I am studying ………English and……Math this term", NULL, "text", "single", "ø/the, the/the, the/ ø, ø/ ø", "");

INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("13", "I dont't think Jokn looks well. He seems ______ ", NULL, "text", "single", "fairly tired, fair tired, fair tiredly, fairly tiredly", "1");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("13", "Which do you prefer - the blue china or the white china? The white china is ______ ", NULL, "text", "single", "definite better, better definite, better definitely, definitely better", "4");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("13", "Were you pleased with the translation? Yes, the job was ______ ", NULL, "text", "single", "amazing satisfactory, amazingly satisfactory, amazing satisfactorily, satisfactory amazing", "2");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("13", "What was you impression of last night's lecture?  ______ speaking, I thought it was rather boring", NULL, "text", "single", "Honest, Honestly, Very, Really", "2");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("13", "How tall is Ralph? He's  ______ than you are", NULL, "text", "single", "slight tall, slight taller, slightly tall, slightly taller", "4");

INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("14", "I have studied English ___ I was 10 years old", NULL, "text", "single", "Because, When, Since, As", "3");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("14", " ____ I finish studying, I will go abroad", NULL, "text", "single", "As, As if, When, Where", "3");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("14", " _____she finishs the homework, she will go to sleep", NULL, "text", "single", "As soon as, As if, When, Seeing that", "1");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("14", "Someone called me ___ I was taking bath", NULL, "text", "single", "Where, When, As, So that", "3");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("14", "____ she got married, Marry changed completely", NULL, "text", "single", "before, After, When, So", "2");

INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("15", "I ______ watch the movie last night. My TV was broken", NULL, "text", "single", "could, can't, couldn't", "3");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("15", "I ______ open the door last night, the key was stuck in it!", NULL, "text", "single", "couldn't, could, can", "1");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("15", "______ you hear that storm yesterday?", NULL, "text", "single", "Can, Can't, Could", "3");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("15", "I enjoyed my trip to Paris because I ______ speak a little French", NULL, "text", "single", "could, couldn't, can", "3");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("15", "______ you speak Russian when you went to the university in Moscow or did you learn later?", NULL, "text", "single", "Can, Could, Couldn't", "2");

INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("16", "Mary is the……….in her class", NULL, "text", "single", "tall, tallest, taller, the taller", "2");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("16", "In Viet Nam, it is normally……………. in the South than in the North", NULL, "text", "single", "hot, hotter, hottest, hoter", "2");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("16", "The food is …………… than the last time I ate it", NULL, "text", "single", "badder, bad, worse, worst", "3");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("16", "Ho Chi Minh city is ………….. than Hanoi", NULL, "text", "single", "big, bigger, biggest, biger", "2");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("16", "Children often learn very ……………….. things around them", NULL, "text", "single", "quickly, quicker, quickest, quick", "2");

INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("17", "If you ___________ my advice, you'll accept it", NULL, "text", "single", "will be taking, will take, are taking, take", "4");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("17", "If we ___________ a few more days", NULL, "text", "single", "hang on, are hanging on, will hang on, will be hanging on", "1");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("17", "If you _________, I'll tell Jagger that we need time to think it over", NULL, "text", "single", "want, are wanting, will want, would want", "1");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("17", "When he ____________ that, he'll be a bit impatient", NULL, "text", "single", "is hearing, will hear, would hear, hears", "4");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("17", "I'm sure that if I _____________ to him sweetly enough he'll hold on and not look elsewhere", NULL, "text", "single", "'m talking, will talk, talk, would talk", "3");

INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("18", "My father usually helps me_______ English", NULL, "text", "single", "to learn, learn, learning, both a and b", "4");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("18", "He was heard_______ shout", NULL, "text", "single", "to, of, by, at", "1");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("18", "This student expected_______ the first winner of the Grand Prix", NULL, "text", "single", "be, being, to be, will be", "3");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("18", "I told her_______ about her wedding; everything will straighten out", NULL, "text", "single", "Don't worry, not to worry, no worry, not worry", "2");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("18", "May I suggest you let_______", NULL, "text", "single", "Mary doing so, Mary do so, Mary does so, Mary to do so", "3");

INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("19", "I (have)___________ a good time tonight", NULL, "text", "single", "is going to have, are going to have, am going to have", "3");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("19", "Janet (help)___________ me", NULL, "text", "single", "is going to help, are going to help, am going to help", "1");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("19", "(he/ drive)__________ the car?", NULL, "text", "single", "is he going to drive, am he going to drive, are he going to drive", "1");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("19", "We (stay)__________ at home tonight", NULL, "text", "single", "are going to stay, am going to stay, is going to stay", "1");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("19", "(you/ play)__________ tennis with Jenny?", NULL, "text", "single", "am you going to play, is you going to play, are you going to play", "3");

INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("20", "The teacher said: `You _______ do all exercises on page 21 in Look Ahead.`", NULL, "text", "single", "must, have to", "1");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("20", "I _________ help my little brother more. My father said so", NULL, "text", "single", "must, have to", "2");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("20", "I _______ take these medicines. The doctor said so", NULL, "text", "single", "must, have to", "2");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("20", "I ________ write lines as a punishment because I threw the shoe of my neighbour through the window", NULL, "text", "single", "must, have to", "2");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("20", "Sorry, I can't come. I ______ clean my room. I can't live in such a mess anymore", NULL, "text", "single", "must, have to", "1");

INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("21", "No _____", NULL, "text", "single", "smoke, to smoke, smoking", "3");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("21", "Don’t______ it", NULL, "text", "single", "touch, to touch, touching", "1");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("21", "Will you______a coffee please?", NULL, "text", "single", "made, to make, make", "3");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("21", "Do________quiet!", NULL, "text", "single", "be, to be, being", "1");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("21", "She asked me _______ the report", NULL, "text", "single", "write, to write, wrote", "2");

INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("22", "Alice saw/ was seeing the accident when she was catching the bus", NULL, "text", "single", "saw, was seeing", "1");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("22", "What were you doing/ did you do when I called?", NULL, "text", "single", "were you doing, did you do", "1");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("22", "I didn’t visit/ weren’t visiting my friends last summer holiday", NULL, "text", "single", "didn't visit, weren't visiting", "1");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("22", "It rained/ was raining heavily last July", NULL, "text", "single", "rained, was raining", "1");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("22", "While people were talking to each other, he read/ was reading his book", NULL, "text", "single", "read, was reading", "2");


INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("23", "Where his wife (be) ………………..?", NULL, "text", "single", "am, is, are, be", "2");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("23", "Jack (wear) ………………..suit today", NULL, "text", "single", "is wearing, are wearing, am wearing, wears", "1");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("23", "The weather (get) ………………..warm this season", NULL, "text", "single", "gets, are getting, is getting, are gets", "3");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("23", "My kids (be)…………. downstairs now. They (play) …………..chess", NULL, "text", "single", "am - am playing, is - is playing, are - are playing, be - being", "3");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("23", "Look! The train (come)…………………", NULL, "text", "single", "are coming, is coming, are come, is come", "2");

INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("24", "When ____________ the school?", NULL, "text", "single", "have you joined, did you joined, did you join, have you ever joined", "3");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("24", "_____________ in England?", NULL, "text", "single", "Did you ever worked, Have you ever worked, Worked you, Didn't you have worked", "2");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("24", "That's the best speech _________", NULL, "text", "single", "I never heard, I didn't hear, I used to hear, I've ever heard", "4");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("24", "He's the most difficult housemate _____________________", NULL, "text", "single", "I never dealt with, I never had to deal with, I've ever had to deal with, I've never had to deal with", "3");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("24", "______ to him last week", NULL, "text", "single", "I spoke, I've already spoken, I didn't spoke, I speaked", "3");

INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("25", "There wasn’t ……………. snow last night", NULL, "text", "single", "many, much, few, a large number of", "2");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("25", "……………the students in my class enjoy taking part in social activities", NULL, "text", "single", "Most of, Most, Many, The number of", "1");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("25", "He’s always busy. He has ………… time to relax", NULL, "text", "single", "much, little, a little, plenty of", "2");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("25", "She put so ………… salt in the soup that she couldn’t have it. It was too salty", NULL, "text", "single", "many, little, much, a little", "3");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("25", "He made too ………….. mistakes in his writing", NULL, "text", "single", "a few, much, many, a number of", "3");

INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("26", "If we _____ cold, we _____ ", NULL, "text", "single", "are - shiver, are - shivering, are - shivered, were - shiver", "1");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("26", "I usually _____ to school if I _____ enough time", NULL, "text", "single", "been walked -  having, walk - have, walk - has, walked - would have", "2");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("26", "What _______ you _________ to eat?", NULL, "text", "single", "will - like, would - like to, would - like, will - like to", "3");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("26", "I ________ _________ a hot dog", NULL, "text", "single", "would like, will - like, would - like to, will - like to", "1");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("26", "What ________ she ________?", NULL, "text", "single", "will - like, would - like to, will - like to, would - like", "4");

INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("27", "I don’t like this book . It is  ______ interesting ______ cheap", NULL, "text", "single", "both - and, either - or, neither - nor, not only - but also", "3");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("27", "Neither Linda nor I  ______ classical music", NULL, "text", "single", "liking, liked, like, likes", "3");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("27", "Tha baby is only two moths old. He can  ______  speak ______  walk", NULL, "text", "single", "neither - nor, either - or, both - and, not - nor", "1");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("27", "He   ______  a teacher or a doctor", NULL, "text", "single", "is neither, neither is, is either, either is", "3");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("27", "She is  ______  friendly  ______  intelligent so I can't help admiring her", NULL, "text", "single", "not only - but also, either - or, both - and, A&C are correct", "4");

INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("28", "If I __________ more money, I would buy a car", NULL, "text", "single", "have, had, would have, will have", "2");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("28", "If she __________ how to speak French, she would not take lessons", NULL, "text", "single", "knows, know, knew, known", "3");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("28", "If he were older, he __________ vote", NULL, "text", "single", "will, could, can, will be able to", "2");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("28", "The men would have money if they _________", NULL, "text", "single", "work, works, worked, working", "3");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("28", "What would you do if you __________ the lottery?", NULL, "text", "single", "win, will win, won, have won", "3");

INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("29", "If I had known that you couldn't eat octopus, I (not buy) _________________ it", NULL, "text", "single", "would be not buy, will not buy, don't buy, wouldn't have bought", "4");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("29", "I (bring) _________________ you some beer if I had known that you were thirsty", NULL, "text", "single", "will bring, would have brought, bring, brought", "2");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("29", "If you had touched that electric cable, you (be) _________________ electrocuted", NULL, "text", "single", "are, would have been, will be, were", "2");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("29", "If the story hadn't been true, the newspaper (not print) _________________ it", NULL, "text", "single", "wouldn't have printed, doesn't print, is print, printing", "1");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("29", " If I __________the same problem you had as a child, I might not have succeeded in life as well as you have", NULL, "text", "single", "have, would have, had had, should have", "3");

INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("30", "I don't know ..... He love her", NULL, "text", "single", "What, Whe, Where, Why", "4");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("30", "Our teacher announce ...... We will go to camping", NULL, "text", "single", "Whose/Where, Whom/Whose, When/Where, What/When", "3");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("30", "I have no idea ...... the interview will take", NULL, "text", "single", "How many, How long, How old, How about", "2");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("30", "The teacher asked us .....  book was on his desk", NULL, "text", "single", "Whose, Whom, Who, Where", "1");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("30", "Do you know ..... the bus run at night?", NULL, "text", "single", "How often, How old, How about, How much", "1");

INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("31", "I ________ during rush hour", NULL, "text", "single", "will be driving, will have drive, will be drive", "1");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("31", "He will not be _____ the bus today", NULL, "text", "single", "take, taken, taking", "3");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("31", "They ________ the cottage that weekend", NULL, "text", "single", "using, ‘ll be using, ‘re be using", "2");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("31", "Nigel _____ be coming to the picnic", NULL, "text", "single", "won’t, won’t not, willn’t", "1");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("31", "Where ________ sleeping?", NULL, "text", "single", "you be, will you, will you be", "3");

INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("32", "The sun shone _______ brightly that she had to put on her glasses", NULL, "text", "single", "so, such, enough, too", "1");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("32", "We had _________ wonderful memories of that place that we decided to return", NULL, "text", "single", "so, such, enough, too", "2");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("32", "It was ________ a nice day that we decided to go to the beach", NULL, "text", "single", "so, such, enough, too", "2");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("32", "I’ m not rich ___________to help you", NULL, "text", "single", "so, such, enough, too", "3");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("32", "This room is ___________ dark for us to study", NULL, "text", "single", "so, such, enough, too", "4");

INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("33", "I was just wondering whether you ____ be able to help me", NULL, "text", "single", "may, might", "2");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("33", "____ God have mercy on your soul", NULL, "text", "single", "may, might", "1");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("33", "You ____ well be right", NULL, "text", "single", "may, might", "1");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("33", "You ____ have told me earlier!", NULL, "text", "single", "may, might", "2");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("33", "You ____ try asking her for help- she knows her stuff", NULL, "text", "single", "may, might", "2");

INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("34", "My husband is waiting for me. I….. not be late", NULL, "text", "single", "should, must, had better, ought to", "3");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("34", "You …… start eating better", NULL, "text", "single", "should, must, had better, ought to", "1");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("34", "I ……. study tonight, but I think I’ll watch TV instead", NULL, "text", "single", "should, must, had better, ought to", "4");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("34", "You …… take care of that cut on your hand soon, or it will get infected", NULL, "text", "single", "should, must, had better, ought to", "3");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("34", "You have got a toothache. Perhaps you ….. see a dentist", NULL, "text", "single", "should, must, had better, ought to", "1");

INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("35", "He advised me to take an English course. I ___ it early", NULL, "text", "single", "should have taken, should take, will have taken, may take", "1");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("35", "It must ___ without delay", NULL, "text", "single", "be done, have been done, do, be doing", "1");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("35", "By the time a baby has reached his first birthday, he should ___ sit up or even stand up", NULL, "text", "single", "to be able to, able to, to be able, be able to", "4");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("35", "You ___ ring the bell; I have a key", NULL, "text", "single", "mustn't, needn't, couldn't, shouldn't", "2");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("35", "My mother permitted me to go out at night. She said, “You ___ go out tonight.”", NULL, "text", "single", "may, have to, must, ought to", "1");

INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("36", "Where ............ you born?", NULL, "text", "single", "were, have, are", "1");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("36", "Where ....................... that jacket? - In that new clothes shop in Piazza Kennedy", NULL, "text", "single", "have you bought, did you buy", "2");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("36", "How long .................. your best friend?", NULL, "text", "single", "do you know, did you know, have you known", "3");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("36", "I lived in Milan when I was younger - Really? How long ........................ there?", NULL, "text", "single", "did you live, have you lived, lived you", "1");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("36", "Gladstone ............... the Prime Minister of Great Britain 5 times during the reign of Queen Victoria", NULL, "text", "single", "has been, had been, was", "3");

INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("37", "She _________ the ocean before she moved to Vancouver", NULL, "text", "single", "had never seen, never seen, have never seen, had never saw", "1");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("37", "The teacher ________ out when I arrived in the classroom", NULL, "text", "single", "goes, have gone, has gone, had gone", "4");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("37", "We should call Rita, _______________?", NULL, "text", "single", "should we, shouldn’t we, shall we, should not we", "2");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("37", "Monkeys can’t sing, ______________?", NULL, "text", "single", "can they, can it, are they, aren't they", "1");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("37", "These books aren’t yours, ____________?", NULL, "text", "single", "are these, aren't these, are they, aren't they", "3");

INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("38", "By 9 o'clock we (cook)____________ dinner", NULL, "text", "single", "Will have cooked, Will cook, Will cooked", "1");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("38", "In one week he (cross)________ the Atlantic by boat", NULL, "text", "single", "Crosses, Cross, Will have crossed", "3");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("38", "Jane (not / finish)___________ her work", NULL, "text", "single", "single", "Will have not finished, Will not have finished, Will finish", "2");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("38", "Fred (not / return) from his holiday by Monday", NULL, "text", "Will not have returned, Will have not returned, Will return", "1");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("38", "She (go)_________ home", NULL, "text", "single", "Will have gone, Will have went, Will have go", "1");

INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("39", "By November I _____ (work) for this company for 6 years", NULL, "text", "single", "will have worked, will have been working", "2");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("39", "By March 15, I ______ (be) here for one year", NULL, "text", "single", "will have been, will have been being", "2");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("39", "By this time next week, he ______ (write) his novel  for 6 months", NULL, "text", "single", "will have written, will have been writing", "2");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("39", "You _______ (finish) your work by 9 tonight?", NULL, "text", "single", "Will you have finished, Will you have been finishing", "1");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("39", "By 2013 we ______ (live) in London for 14 years", NULL, "text", "single", "will have lived, will have been living", "2");

INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("40", "The story was very funny. The math teacher told the story", NULL, "text", "single", "The story that the math teacher told was very funny, The story which the math teacher told was very funny, The story the math teacher told was very funny, All are correct", "4");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("40", "The girl went to the police station. Her case was stolen", NULL, "text", "single", "The girl whose case was stolen went to the police station, The girl her case was stolen went to the police station, The girl the case of which was stolen went to the police station, The girl who’s case was stolen went to the police station", "1");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("40", "Is the man your father? The man is standing at the gate", NULL, "text", "single", "Is the man whom is standing at the gate your father?, Is the man who is standing at the gate your father?, Is the man  standing at the gate your father?, Both B and C are correct", "4");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("40", "Can the students give back their books? The students are leaving tomorrow", NULL, "text", "single", "Can the students whom are leaving tomorrow give back their books?, Can the students who leaving tomorrow give back their books?, Can the students leaving tomorrow give back their books?, Can the students whose leaving tomorrow give back their books?", "3");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("40", "The children were attracted by the show. It was performed by the animals", NULL, "text", "single", "The children attracted by the show which was performed by the animals, The children were attracted by the show to have been performed by the animals, The show performing by the animals attracted the children, The children were attracted by the show performed by the animals", "4");

INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("41", "Before I came to Northern Europe I ___________ snow!", NULL, "text", "single", "had never seen, had never been seeing", "1");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("41", "When police were investigating the road accident they discovered that the driver ___________ 2 road accidents before", NULL, "text", "single", "had been involved in, had been being involved in", "1");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("41", "When we ___________ the tour of the city we decided to go and eat in a local restaurant", NULL, "text", "single", "had done, had been doing", "1");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("41", "When I got home I realised that while I ___________ someone had stolen my wallet!", NULL, "text", "single", "had walked, had been walking", "2");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("41", "The restaurant was very slow. When we went I ___________ all of my meal before my friends’ meals arrived!", NULL, "text", "single", "had already eaten, had already been eating", "2");

INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("42", "Jack asked me _____", NULL, "text", "single", " where do you come from?, where I came from, where I came from, where did I come from?", "3");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("42", "She asked me _____ I liked pop music", NULL, "text", "single", "when, what, if, x", "3");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("42", "The doctor ____ him to take more exercise", NULL, "text", "single", "told, tell, have told, are telling", "1");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("42", "I wanted to know_____ return home", NULL, "text", "single", "when would she, when will she, when she will, when she would", "4");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("42", "Claire told me that her father____ a race horse", NULL, "text", "single", "owns, owned, owning, A and B", "4");

INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("43", "I am………….milk every day", NULL, "text", "single", "used to drink, used to drinking, use to drink", "2");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("43", "She has………….in a small village", NULL, "text", "single", "got used to, get used to, got used to living", "3");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("43", "When I was a child, I didn’t……………chocolate but now I eat a lot", NULL, "text", "single", "use to eating, use to eat, used to eat", "2");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("43", "You must…………….English for long hours", NULL, "text", "single", "used to learning, used learn, use to learn, get used to learning", "4");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("43", "I have……………….English every day", NULL, "text", "single", "use to learn, used to learning, used learning, got used to learning", "4");

INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("44", "If only my boyfriend_____ in time to pick me up", NULL, "text", "single", "comes, come, came, has come", "3");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("44", "I was here for only a week. If only I _____ more time there but I had to move to Paris", NULL, "text", "single", "had, would have, had had, has", "3");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("44", "If only my parents_____ to me", NULL, "text", "single", "listens, listen, have listened, listened", "4");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("44", "If only she (finish) _____ her homework last night", NULL, "text", "single", "will finish, finished, have finished, had finished", "4");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("44", "If only my dad _____smoke", NULL, "text", "single", "do, did, doesn't, didn't", "4");



INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("45", "I _____ from France", NULL, "text", "single", "is, are, am, be", "3");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("45", "this is my friend. _____ name is Peter", NULL, "text", "single", "Her, Our, Yours, His", "4");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("45", "Mike is _____", NULL, "text", "single", "my sister's friend, friend my sister, friend from my sister, my sister friend's", "1");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("45", "My brother is _____ artist", NULL, "text", "single", "the, an , a, -", "2");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("45", "_____ 20 desks in the classroom", NULL, "text", "single", "This is, There is, They are, There are", "4");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("45", "Paul _____ romantic films", NULL, "text", "single", "likes not, don't like, doesn't like, isn't like", "3");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("45", "Sorry, I can't talk. I _____ right now", NULL, "text", "single", "driving, am driving, drives, drive", "2");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("45", "She _____ at school last week", NULL, "text", "single", "didn't be, weren't, wasn't, isn't", "3");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("45", "_____ the film last night", NULL, "text", "single", "like, likes, liking, liked", "4");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("45", "_____ a piece of cake? No, thank you.", NULL, "text", "single", "Do you like, Would you like, Want you, Are you like", "2");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("45", "The living room is _____ than the bedroom", NULL, "text", "single", "more big, more bigger, biggest, bigger", "4");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("45", "The car is very old. We are going _____ a new car soon", NULL, "text", "single", "to buy, buying, to will buy, buy", "1");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("45", "Jane is a vegetarian. She _____ meat", NULL, "text", "single", "sometimes eats, never eats, often eats, usually eats", "2");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("45", "There aren't _____ buses late in the evening", NULL, "text", "single", "some, any, no, a", "2");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("45", "The car park is _____ to the restaurant", NULL, "text", "single", "next, oppostite, behind, in front", "1");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("45", "Sue _____ shopping every day", NULL, "text", "single", "is going, go, going, goes", "4");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("45", "They _____ in the park when it started to rain heavily", NULL, "text", "single", "walked, were walking, were walk, are walking", "2");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("45", "_____ seen fireworks before", NULL, "text", "single", "Did you ever, Are you ever, Have you ever, Do you ever", "3");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("45", "We've been friends _____ many years", NULL, "text", "single", "since, from, during, for", "4");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("45", "You _____ pay for the tickets. They're free", NULL, "text", "single", "have to, don't have to, don't need to ,doesn't have to", "3");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("45", "Jeff was ill last week and he _____ go out", NULL, "text", "single", "needn't, can't, mustn't, couldn't", "4");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("45", "These are photos _____ I took on holiday", NULL, "text", "single", "which, who, what, where", "1");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("45", "We'll stay at home if it _____ this afternoon", NULL, "text", "single", "raining, rains, will rain, rain", "2");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("45", "He doesn't smoke now, but he _____ a lot when he was young", NULL, "text", "single", "has smoked, smokes, used to smoke, was smoked", "3");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("45", "Mark plays football _____ anyone else I know", NULL, "text", "single", "more good than, as better as, best than, better than", "4");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("45", "I promise I _____ you as soon as I've finished this cleaning", NULL, "text", "single", "will help, am helping, going to help, have helped", "1");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("45", "This town _____ by a lot of tourists during the summer", NULL, "text", "single", "visits, visited, is visiting, is visited", "4");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("45", "He said that his friends _____ to speak to him after they lost the football match", NULL, "text", "single", "not want, weren't, didn't want, aren't wanting", "3");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("45", "How about _____ to the cinema tonight?", NULL, "text", "single", "going, go, to go, for going", "1");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("45", "Excuse me, can you _____ me the way to the station, please?", NULL, "text", "single", "give, take, tell, say", "3");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("45", "I wasn't interested in the performance very  much. _____", NULL, "text", "single", "I didn't too, Neither was I, Nor I did, So I wasn't", "2");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("45", "Take a warm coat, _____ you may get very cold outside", NULL, "text", "single", "otherwise, in case, so that, in order to", "1");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("45", "_____ this great book and I can't wait to see how it ends", NULL, "text", "single", "I don't read, I've read, I've been reading, I read", "3");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("45", "What I like more than anything else _____ at weekends", NULL, "text", "single", "playing golf, to play golf, is playing golf, is play golf", "3");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("45", "She _____ for her cat for two days when she finally found it in the garage", NULL, "text", "single", "looked, had been looked, had been looking, were looking", "3");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("45", "We won't catch the plane _____ we leave home now! Please hurry up!", NULL, "text", "single", "if, providing that, except, unless", "4");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("45", "If I hadn't replied to your email, I _____ here with you now", NULL, "text", "single", "can't be, wouldn't be, won't be, haven't been", "2");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("45", "Do you think you _____ with my mobile phone soon? I need to make a call", NULL, "text", "single", "finish, are finishing, will have finished, are finished", "3");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("45", "I don't remember mentioning _____ dinner together tonight", NULL, "text", "single", "go for, you going to, to go for, going for", "4");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("45", "Was it Captain Cook _____ New Zealand", NULL, "text", "single", "who discovered, discovered, that discover, who was discovering", "1");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("45", "You may not like the cold weather here, but you'll have to _____. I'm afraid.", NULL, "text", "single", "tell it off, sort itself out, put up with it, put it off", "3");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("45", "It's cold so you should _____ on a warm jacket", NULL, "text", "single", "put, wear, dress, take", "1");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("45", "Paul will look _____ our dogs while we're on holiday", NULL, "text", "single", "at, for, into, after", "4");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("45", "She _____ a lot of her free time reading", NULL, "text", "single", "does, spends, has, makes", "2");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("45", "Hello, this is Simon. Could I _____ to Jane, please?", NULL, "text", "single", "say, tell, call, speak", "4");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("45", "They're coming to our house _____ Saturday", NULL, "text", "single", "in, at, on, with", "3");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("45", "I think it's very easy to _____ debt these days", NULL, "text", "single", "go into, become, go down to, get into", "4");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("45", "Come on! Quick! Let's get _____ !", NULL, "text", "single", "highlight, cracking, massive, with immediate effect", "2");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("45", "I phoned her _____ I heared the news", NULL, "text", "single", "minute, during, by the time, the monent", "4");
INSERT INTO `quiz_question` (`ID_quiz`, `question`, `questionPic`, `questionType`, `answerSelectionType`, `answers`, `correctAnswer`) VALUES ("45", "I feel very _____. I'm going to go to bed!", NULL, "text", "single", "nap, asleep, sleepy, sleeper", "3");













