// current player constants
export const CURRENT_PLAYER_POINT_INCREASE = "CURRENT_PLAYER_POINT_INCREASE";
export const GENERATE_NEW_WORD_ON_SUCCESS = "GENERATE_NEW_WORD_ON_SUCCESS";

// opponent player constants
export const OPPONENT_PLAYER_CHARACTER_SELECT =
  "OPPONENT_PLAYER_CHARACTER_SELECT";
export const OPPONENT_PLAYER_POINT_INCREASE = "OPPONENT_PLAYER_POINT_INCREASE";


export const GAME_END = "END_GAME";


export const RESET_CURRENT_PLAYER_INFO = "RESET_CURRENT_PLAYER_INFO";
export const RESET_OPPONENT_PLAYER_INFO = "RESET_OPPONENT_PLAYER_INFO";
export const RESET_GAME_STATE = "RESET_GAME_STATE";

export const START_TYPING_COUNTDOWN = "START_TYPING_COUNTDOWN";
export const INCREMENT_CHARACTER_TYPED = "INCREMENT_CHARACTER_TYPED";


export const SET_WORDS_ARRAY = "SET_WORDS_ARRAY";
